# Generated by Django 3.2.13 on 2022-05-22 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_post_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
