# Generated by Django 3.2.13 on 2022-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220522_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_pic',
            field=models.ImageField(blank=True, default='company_pic.png', upload_to='company_pics'),
        ),
    ]
