# Generated by Django 3.2.13 on 2022-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_company_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='education_and_experience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
