# Generated by Django 3.2.13 on 2022-05-26 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20220526_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
